[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_dir = "cache"

[profile.default.rpc_endpoints]
mainnet = "${RPC_URL}"

[profile.default.fork]
url = "${RPC_URL}"
block_number = "${BLOCK_NUMBER}"
